kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pvc
  namespace: factory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: database-pv
